### PR TITLE
Align point titles, move point numbers into margin

### PR DESCRIPTION
**Pull request by 36degrees**
## Before

screen shot 2016-07-05 at 10 34 51

## After
screen shot 2016-07-05 at 10 34 52

### CODE REVIEW

**Comment by 36degrees** [comment]
[Cross browser screenshots](https://www.browserstack.com/screenshots/cae873d751a27cec06b1f21f0589ebe789ba41ea)

**Comment by gemmaleigh** [comment]
I've adjusted the spacing for smaller screens and [taken another set of screenshots](https://www.browserstack.com/screenshots/b1442dfb33fa736895f43b1add74d712a091468b).

**Comment by 36degrees** [comment]
Those screen shots don't appear to show the margin at all now? Was this branch definitely checked out when you took them?

**Comment by 36degrees** [comment]
@gemmaleigh ^

**Comment by gemmaleigh** [comment]
I updated the screenshots, this is good to merge 👍

**Comment by 36degrees** [comment]
@thehenster Given we've both worked on this now, it'd probably be good to get someone else to 2i it? Merge if you're happy with it.

**Comment by thehenster** [comment]
:+1: The existing integration tests are stripping the new tag so no need for an extra test.

**Pull request merged**
