### PR TITLE
Use new page header module

### PR DESCRIPTION
**Pull request by 36degrees**
### Topic
before - topic
### Guide
before - guide
### Service Standard
before - standard
### Point
before - point

### Topic

screen shot 2016-07-05 at 12 53 29

### Guide

screen shot 2016-07-05 at 12 53 37

### Service Standard

screen shot 2016-07-05 at 12 53 11

### Point

screen shot 2016-07-05 at 12 52 57

### CODE REVIEW

**Comment by 36degrees** [comment]
@gemmaleigh would you mind reviewing this one?

**Comment by gemmaleigh** [comment]
Looks like there's some spacing missing under each title - thanks @36degrees for the screenshots, I'll fix that - the before and after should be identical.

**Comment by gemmaleigh** [comment]
Hi @36degrees, I've fixed the spacing issues and updated the "After" set of screenshots. 
The only difference now is in the increase in spacing underneath the page context.

**Comment by 36degrees** [comment]
Happy with your changes, so if you're happy with my changes too then I guess this can be merged?

(Go Teamwork.)

**Comment by gemmaleigh** [comment]
Nice one! 👍

**Pull request merged**
